### ISSUE TITLE
Fatal error: Call to a member function fetch() on null

### ISSUE THREAD

**Issue by grandoc** [Eoxia/doliwpshop#1]
Fatal error: Uncaught Error: Call to a member function fetch() on null in /home/httpd/vhosts/aflac.fr/domains/compta.aflac.fr/httpdocs/custom/wpshop/core/triggers/interface_99_modWpshop_WpshopTriggers.class.php on line 134

**Comment by lmag** [comment]
Bonjour,

On a supprimer de nombreux points je pense que cette issue n'a plus lieux d'être

Bien cordialement
