### ISSUE TITLE
Impossible d'accéder aux paramètres du module

### ISSUE THREAD

**Issue by galereetco** [Eoxia/doliwpshop#14]
La page de configuration du module sur Dolibarr est inaccessible => 404 Introuvable
j'ai testé plusieurs fois. Réinstallé plusieurs fois également.

Le module est inutile du coup puisque c'est via page que l'on est supposé se raccorder à WPshop sur Wordpress

PS: j'utilise la version 12.0.2 de Dolibarr

**Comment by lmag** [comment]
Bonjour,

Peux tu nous donner plus d'information provenance du module téléchargé

Laurent

**Comment by galereetco** [comment]
Bonjour Laurent,

J'ai installé la version master mais j'ai également essayé la version 1.0.1. Le tout téléchargé depuis Github.
A noter que je n'ai pas réussi à l'installer directement via Dolibarr (uniquement en intégrant les fichiers dans le dossier custom), j'avais un message d'erreur sur l'intitulé du fichier ou sur un fichier manquant à l'intérieur.

Merci pour votre aide 👍 
Marion

**Comment by lmag** [comment]
Génial n'hésitez pas à nous tenir informé
