### ISSUE TITLE
[BUG] Affichage des tiers et des produits problématique dans le dashoard et front end

### ISSUE THREAD

**Issue by jbonlinea** [Eoxia/doliwpshop#17]
Dans le dashboard et dans le front, les listes des produits ne s'affiche pas correctement, l'array (ou le tableau) contenant les detail  du produit s'affiche comme si il y avait un "echo print_r()" 

Cela fait la même chose pour les tiers, mais pas en front ou c'est la page du compte qui s'affiche

**Comment by lmag** [comment]
N'est plus d'actualité sur les nouvelles versions
