### ISSUE TITLE
Modification manuelle du stock sur WP

### ISSUE THREAD

**Issue by cedric-eoxia** [Eoxia/doliwpshop#23]
Impossible d'entrer une valeur de stock sur la fiche WordPress.
De ce fait il n'est pas possible de vendre des produits unitaires

![image](https://user-images.githubusercontent.com/18572034/111170209-f9ad9c00-85a3-11eb-8990-b41a8ebb24a7.png)

**Comment by lmag** [comment]
C'est normal la gestion des stock est synchronisée sur le stock de Dolibarr
