### ISSUE TITLE
refonte systeme paiement wpshop

### ISSUE THREAD

**Issue by nicolas-eoxia** [Eoxia/doliwpshop#24]
On va utilisr le paiement avec dolibarr

on doit créer un route api pour récupérer le lien de paiement

les info pour faire ca : 

			// Show online payment link
			$useonlinepayment = (!empty($conf->paypal->enabled) || !empty($conf->stripe->enabled) || !empty($conf->paybox->enabled));
			if (!empty($conf->global->ORDER_HIDE_ONLINE_PAYMENT_ON_ORDER)) $useonlinepayment = 0;
			if ($object->statut != Commande::STATUS_DRAFT && $useonlinepayment)
			{
				print '<br>';
				require_once DOL_DOCUMENT_ROOT.'/core/lib/payments.lib.php';
				print showOnlinePaymentUrl('order', $object->ref).'<br>';
			}

**Comment by lmag** [comment]
Ça me paraît mieux

Le mer. 12 mai 2021 à 18:19, Nicolas Domenech ***@***.***> a
écrit :

**Comment by lmag** [comment]
Commande C2105-0039 et Client APIWPSHOP
******Passage sur Stripe et retour OK
-C2105-0039
-Montant payé sur stripe = 12,00€TTC
--@todo v2 récupération montant commande from stripe (facile ou pas)
Si montant récupéré = montant commande alors
-Fait la facture (C2105-0039;APIWPSHOP) fonction createfromorder
-Affecter le paiement de 12,00TTC (New paiement) sur le compte configuré dans le module stripe ! Si pas configuré bug !
