### ISSUE TITLE
PB de connexion ERP

### ISSUE THREAD

**Issue by jeanmichel83** [Eoxia/doliwpshop#36]
Bonjour, wordpress: 5.8.1, theme: beflex-pro WPshop: 2.5
la clé API est identique sur Dolishop et dolibarr à partir de dolishop le test de connexion est correct
mais j'ai l'erreur de connexion
voir pj
![Screen Shot 11-05-21 at 06 08 PM](https://user-images.githubusercontent.com/63457365/140552220-82ba0057-6a9e-42c8-8ccc-308bcd681172.PNG)

**Comment by jeanmichel83** [comment]
resolue URL était érronée

**Comment by lmag** [comment]
J’adore quand un plan se déroule sans accroc. 👍 
https://www.youtube.com/watch?v=HzRF2622m9A
